#[cfg(feature = "aws")]
pub mod adapters;
#[cfg(feature = "local")]
pub mod app;
pub mod bootstrap;
pub mod build_lambda;
pub mod build_worker;
pub mod contracts;
pub mod embedding;
pub mod error;
pub mod http;
pub mod index;
pub mod indexing;
pub mod lambda_events;
pub mod local;
pub mod models;
pub mod query;
pub mod query_lambda;
pub mod query_service;
pub mod storage;
pub mod write;
pub mod write_lambda;
